messages:
  firstJoinMessages:
    default: <gradient:#FFAA00:#FF55FF>Welcome to Aurora PvP!
  joinMessages:
    default: <gradient:#FFAA00:#FF55FF>Use /kits to select a kit, and go to the kit creator to create a kit!
  auto-messages:
    default: <gradient:#FFAA00:#FF55FF>Remember to go to the kit creator to create a kit!
    discord: <gradient:#FFAA00:#FF55FF>Join our discord! discord.gg/SgZ2jj9Ynr
    reminder: <gradient:#FFAA00:#FF55FF>Remember you can use /ignore to ignore someone!
    interval: 500
  help-command:
    1: <gradient:#FFAA00:#FF55FF>------------------
    2: <gradient:#FFAA00:#FF55FF>/kits - Opens the kits menu
    3: <gradient:#FFAA00:#FF55FF>/kit [name] - Uses a kit
    4: <gradient:#FFAA00:#FF55FF>/createkit - Creates a kit
    5: <gradient:#FFAA00:#FF55FF>/duel [player] - Sends a duel request to a player
    6: <gradient:#FFAA00:#FF55FF>------------------
antispam:
  similarity-detection:
    enable: true
    timeout: 180000
    similarity: .80
    max-violations: 6
    violations-expire: 180
  cooldown:
    enable: false
    time: 1
    max-violations: 6
    violations-expire: 180