name: AuroraChat
version: '${version}'
main: club.aurorapvp.aurorachat.AuroraChat
api-version: '1.20'
authors: [ Villagers654 ]
description: A Chat Plugin for the Aurora Network
website: aurorapvp.club
permissions:
  aurorachat.command.help:
    default: false
  aurorachat.command.ignore:
    default: false
  aurorachat.command.unignore:
    default: false
  aurorachat.command.ignorelist:
    default: false
  aurorachat.command.msg:
    default: false
  aurorachat.command.reply:
    default: false
  aurorachat.command.namecolor:
    default: false
  aurorachat.command.aurorachat.reload:
    default: false
  aurorachat.command.aurorachat.help:
    default: false

  aurorachat.admin:
    description: Enables use of AuroraChat admin commands
    default: op
    children:
      aurorachat.command.aurorachat.reload: true

  aurorachat.namecolor:
    description: Allows changing name color
    default: op
    children:
      aurorachat.command.namecolor: true

  aurorachat.default:
    description: Enables use of AuroraChat basic commands
    default: true
    children:
      aurorachat.command.help: true
      aurorachat.command.ignore: true
      aurorachat.command.unignore: true
      aurorachat.command.ignorelist: true
      aurorachat.command.msg: true
      aurorachat.command.reply: true
      aurorachat.command.aurorachat.help: true

dependencies:
  server:
    Vault:
      required: true