name: AuroraChat
version: '${version}'
main: club.aurorapvp.aurorachat.AuroraChat
api-version: '1.20'
authors: [ Villagers654 ]
description: A Chat Plugin for the Aurora Network
website: aurorapvp.club
commands:
  help:
    description: Opens the help menu
    permission: aurorachat.command.help
  ignore:
    description: Ignores a player
    permission: aurorachat.command.ignore
  unignore:
    description: Uniqnores a player
    permission: aurorachat.command.unignore
  ignorelist:
    description: Returns a list of all ignored players
    permission: aurorachat.command.ignorelist
  msg:
    aliases: [w, tell]
    description: Sends a private message
    permission: aurorachat.command.msg
  reply:
    aliases: [r]
    description: Replies to a private message
    permission: aurorachat.command.reply
permissions:
  aurorachat.command.help:
    default: true
  aurorachat.command.ignore:
    default: true
  aurorachat.command.unignore:
    default: true
  aurorachat.command.ignorelist:
    default: true
  aurorachat.command.msg:
    default: true
  aurorachat.command.reply:
    default: true
  aurorachat.admin:
    description: Enables use of AuroraChat admin commands
    default: op
  aurorachat.default:
    description: Enables use of AuroraChat basic commands
    default: true
    children:
      aurorachat.command.help: true
      aurorachat.command.ignore: true
      aurorachat.command.unignore: true
      aurorachat.command.ignorelist: true
      aurorachat.command.msg: true
      aurorachat.command.reply: true